// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd46q-huF3COA-0q-4lP0UZ9-x_87e1lI',
    appId: '1:502679206932:web:9a93a0e5972f23f7affb01',
    messagingSenderId: '502679206932',
    projectId: 'chatbox-3dac1',
    authDomain: 'chatbox-3dac1.firebaseapp.com',
    storageBucket: 'chatbox-3dac1.appspot.com',
    measurementId: 'G-EEW598JQMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuDD2CsPYRZ6FIbmS82HbYTdmJgdDWZ0s',
    appId: '1:502679206932:android:d8a2ea6bb7b1c0f1affb01',
    messagingSenderId: '502679206932',
    projectId: 'chatbox-3dac1',
    storageBucket: 'chatbox-3dac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0vh7mSLvd85Rl6QawBX6BtiAEstAAWE',
    appId: '1:502679206932:ios:4c1a899c63bff07daffb01',
    messagingSenderId: '502679206932',
    projectId: 'chatbox-3dac1',
    storageBucket: 'chatbox-3dac1.appspot.com',
    iosClientId: '502679206932-ceu8vrnkihi1odmhesua4pg5b3686mgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0vh7mSLvd85Rl6QawBX6BtiAEstAAWE',
    appId: '1:502679206932:ios:4c1a899c63bff07daffb01',
    messagingSenderId: '502679206932',
    projectId: 'chatbox-3dac1',
    storageBucket: 'chatbox-3dac1.appspot.com',
    iosClientId: '502679206932-ceu8vrnkihi1odmhesua4pg5b3686mgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
